import type { Incident, PriceData, AirspaceData } from '@/hooks/useDataPipeline'

export function exportSitrep(incidents: Incident[], prices: PriceData | null, airspace: AirspaceData | null) {
  const t = new Date().toISOString()
  const p = prices ?? {} as PriceData

  // Derive real stats from pipeline
  const kinetic = incidents.filter(i => {
    const raw = (i.type || i.title || '').toLowerCase()
    return raw.includes('missile') || raw.includes('airstrike') || raw.includes('drone') || raw.includes('ballistic')
  }).length
  const confirmed = incidents.filter(i => i.status === 'confirmed').length
  const countries = new Set(incidents.map(i => i.location?.country).filter(Boolean))
  const sources = new Set(incidents.map(i => i.source).filter(Boolean))
  let milCas = 0, civCas = 0
  for (const inc of incidents) {
    milCas += inc.casualties?.military ?? 0
    civCas += inc.casualties?.civilian ?? 0
  }

  const lines = [
    '═══════════════════════════════════════════════',
    'HADAL THREAT INTELLIGENCE TERMINAL',
    'TACTICAL SITREP · ' + t,
    '═══════════════════════════════════════════════',
    'THEATRE: GULF / MIDDLE EAST',
    'CLASSIFICATION: OSINT UNCLASSIFIED',
    'GENERATED BY: HADAL v2.0',
    '',
    `■ DATA PIPELINE: ${incidents.length > 0 ? 'LIVE · ' + incidents.length + ' INCIDENTS' : 'OFFLINE — NO LIVE DATA'}`,
    '',
    '■ INCIDENT SUMMARY:',
    `  TOTAL TRACKED: ${incidents.length}`,
    `  KINETIC EVENTS: ${kinetic}`,
    `  CONFIRMED: ${confirmed}`,
    `  COUNTRIES AFFECTED: ${countries.size} (${[...countries].join(', ') || '—'})`,
    `  UNIQUE SOURCES: ${sources.size}`,
    `  MILITARY CASUALTIES (REPORTED): ${milCas > 0 ? milCas.toLocaleString() : '—'}`,
    `  CIVILIAN CASUALTIES (REPORTED): ${civCas > 0 ? civCas.toLocaleString() : '—'}`,
    '',
    `■ AIRSPACE: ${airspace?.total_notams ?? '—'} NOTAMS · CRITICAL: ${airspace?.severity_counts?.CRITICAL ?? '—'}`,
    '',
    '■ ECONOMIC CONTEXT:',
    '  BRENT CRUDE: ' + (p.brent ? '$' + p.brent.price.toFixed(2) + ' (' + (p.brent.formatted_change ?? '') + ')' : 'N/A'),
    '  GOLD: ' + (p.gold ? '$' + p.gold.price.toFixed(0) + ' (' + (p.gold.formatted_change ?? '') + ')' : 'N/A'),
    '  NAT GAS: ' + (p.gas ? '$' + p.gas.price.toFixed(3) + ' (' + (p.gas.formatted_change ?? '') + ')' : 'N/A'),
    '  BITCOIN: ' + (p.bitcoin ? '$' + p.bitcoin.price.toLocaleString() + ' (' + (p.bitcoin.formatted_change ?? '') + ')' : 'N/A'),
    '',
    '■ RECENT INCIDENTS (LAST 15):',
    ...(incidents.length > 0
      ? incidents.slice(0, 15).map(i => `  [${(i.type ?? '—').toUpperCase()}] ${(i.title ?? '').slice(0, 80)} · ${i.source ?? 'OSINT'} · CONF ${i.credibility ?? '—'}%`)
      : ['  (no live data available)']),
    '',
    'NOTE: All data derived from OSINT pipeline. Casualty figures are unverified estimates.',
    'SOURCE: HADAL OSINT PIPELINE',
    '═══════════════════════════════════════════════',
  ].join('\n')
  const blob = new Blob([lines], { type: 'text/plain' })
  const a = document.createElement('a')
  a.href = URL.createObjectURL(blob)
  a.download = 'HADAL_SITREP_' + t.slice(0, 10) + '.txt'
  a.click()
  URL.revokeObjectURL(a.href)
}
