import type { Incident, PriceData, AirspaceData } from '@/hooks/useDataPipeline'

export function exportSitrep(incidents: Incident[], prices: PriceData | null, airspace: AirspaceData | null) {
  const t = new Date().toISOString()
  const p = prices ?? {} as PriceData
  const lines = [
    '═══════════════════════════════════════════════',
    'HADAL THREAT INTELLIGENCE TERMINAL',
    'TACTICAL SITREP · ' + t,
    '═══════════════════════════════════════════════',
    'THEATRE: GULF / MIDDLE EAST',
    'CLASSIFICATION: OSINT UNCLASSIFIED',
    'GENERATED BY: HADAL v2.0 / MASTERBLOX CAPITAL',
    '',
    '■ DATA PIPELINE STATUS: ' + (incidents.length > 0 ? 'LIVE · ' + incidents.length + ' INCIDENTS' : 'STATIC'),
    '■ THEATRE STATUS: CRITICAL — ACTIVE CONFLICT',
    '■ INTERCEPTIONS CONFIRMED: 1,160+',
    '■ THAAD NODES DEGRADED: 5 of 5',
    '■ AIR DEFENCE COVERAGE: 61% (DEGRADED)',
    '■ AIRSPACE CRITICAL NOTAMS: ' + (airspace?.severity_counts?.CRITICAL ?? '—'),
    '',
    '■ STRIKE DATA:',
    '  UAE: 165 BALLISTIC + 2 CRUISE + 541 DRONES · 35 IMPACTS',
    '  KUWAIT: 97 BALLISTIC + 283 DRONES INTERCEPTED',
    '  QATAR: 18 ENGAGED · UEWR RADAR DESTROYED ($1.1B)',
    '  BAHRAIN: 45 MISSILES + 9 DRONES · 5TH FLEET HQ HIT',
    '  JORDAN: MUWAFFAQ THAAD DESTROYED (SAT MAR 2)',
    '',
    '■ ECONOMIC INTELLIGENCE:',
    '  BRENT CRUDE: ' + (p.brent ? '$' + p.brent.price.toFixed(2) + ' (' + (p.brent.formatted_change ?? '') + ')' : 'N/A'),
    '  GOLD: ' + (p.gold ? '$' + p.gold.price.toFixed(0) + ' (' + (p.gold.formatted_change ?? '') + ')' : 'N/A'),
    '  NAT GAS: ' + (p.gas ? '$' + p.gas.price.toFixed(3) + ' (' + (p.gas.formatted_change ?? '') + ')' : 'N/A'),
    '  BITCOIN: ' + (p.bitcoin ? '$' + p.bitcoin.price.toLocaleString() + ' (' + (p.bitcoin.formatted_change ?? '') + ')' : 'N/A'),
    '',
    '■ LIVE OSINT FEED (LAST 15):',
    ...(incidents.length > 0
      ? incidents.slice(0, 15).map(i => `  [${(i.type ?? '—').toUpperCase()}] ${(i.title ?? '').slice(0, 80)} · ${i.source ?? 'OSINT'} · CONF ${i.credibility ?? '—'}%`)
      : ['  (no live data — static fallback)']),
    '',
    'DATA SOURCES: HADAL OSINT PIPELINE / IRANWARLIVE / MoD VERIFIED',
    '═══════════════════════════════════════════════',
  ].join('\n')
  const blob = new Blob([lines], { type: 'text/plain' })
  const a = document.createElement('a')
  a.href = URL.createObjectURL(blob)
  a.download = 'HADAL_SITREP_' + t.slice(0, 10) + '.txt'
  a.click()
}
